# Training settings
save_model: True
num_workers: 0
progress_bar: False
gpus: 1            # Multi-gpu is not implemented on this branch
clip_grad: null          # float, null to disable
log_every_steps: 5
seed: 0