conditional: False
diffusion_noise_schedule: 'cosine'
T: 500
GraphTransformer:
  n_layers: 8
  hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}
  hidden_dims: {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128} # dx_d = dx_n